version: '3.8'

services:
  backend:
    build: ./backend
    container_name: skillindia_backend
    ports:
      - "5000:5000"
    command: sh -c "node seed.js && node server.js"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/skillindiaconnect
      - PG_USER=postgres
      - PG_HOST=postgresdb
      - PG_DATABASE=skillindiaconnect
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - JWT_SECRET=supersecretjwtkey_for_academic_project
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
    depends_on:
      - mongodb
      - postgresdb
    networks:
      - skillindia_network

  mongodb:
    image: mongo:latest
    container_name: skillindia_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - skillindia_network

  postgresdb:
    image: postgres:15
    container_name: skillindia_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skillindiaconnect
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - skillindia_network

volumes:
  mongo_data:
  pg_data:

networks:
  skillindia_network:
    driver: bridge
